fix(ci): code format check now fails on white space only errors. (#311)

diff --git a/.yamato/code-format-check.yml b/.yamato/code-format-check.yml
--- a/.yamato/code-format-check.yml
+++ b/.yamato/code-format-check.yml
@@ -1,4 +1,10 @@
 {% metadata_file .yamato/package.metafile -%}
+
+format_paths: Docs
+      Packages/com.unity.cloud.gltfast
+      Packages/com.unity.cloud.gltfast.tests/package.json
+      Packages/com.unity.cloud.gltfast.tests/Tests
+      Tools
 ---
 code_format_check:
   name : Code Format check
@@ -12,29 +18,23 @@ code_format_check:
       GIT_CLONE_PROTECTION_ACTIVE=false
       git clone --depth 1 --branch stable https://github.cds.internal.unity3d.com/unity/unity-meta.git
     - mv unity-meta ~
-    - >
-      perl ~/unity-meta/Tools/Format/format.pl
-      --preview
-      Docs
-      Packages/com.unity.cloud.gltfast
-      Packages/com.unity.cloud.gltfast.tests/package.json
-      Packages/com.unity.cloud.gltfast.tests/Tests
-      Tools
     - |
-      if [ -s format.patch ]
-      then
-        echo "Install jq"
-        sudo apt-get install jq
-        echo "Creating Result"
-        echo '{"title":"Code Format Check","conclusion":"failure","tags":["code-format","slack"],"resultType":"userFriendly","summary":"Some files have incorrect formatting! The `code_format_patch` artifact contains a patch that fixes it.","data":' > result.json
-        cat format.patch | jq -Rs . >> result.json
-        echo '}' >> result.json
-        curl -X POST -d @result.json -H 'Content-Type: application/json' $YAMATO_REPORTING_SERVER/result
-        echo "Failing job"
-        exit -1
-      else
-        curl -X POST -d "{\"title\": \"Code Format Check\",\"conclusion\": \"success\"}" -H 'Content-Type: application/json' $YAMATO_REPORTING_SERVER/result
-      fi
+      (
+      perl ~/unity-meta/Tools/Format/format.pl --dry-run {{ format_paths }} &&
+      curl -X POST -d "{\"title\": \"Code Format Check\",\"conclusion\": \"success\"}" -H 'Content-Type: application/json' $YAMATO_REPORTING_SERVER/result
+      ) || (
+      perl ~/unity-meta/Tools/Format/format.pl --preview {{ format_paths }}
+      echo "Install jq"
+      sudo apt-get install jq
+      echo "Creating Result"
+      echo '{"title":"Code Format Check","conclusion":"failure","tags":["code-format","slack"],"resultType":"userFriendly","summary":"Some files have incorrect formatting! The `code_format_patch` artifact contains a patch that fixes it.","data":' > result.json
+      cat format.patch | jq -Rs . >> result.json
+      echo '}' >> result.json
+      curl -X POST -d @result.json -H 'Content-Type: application/json' $YAMATO_REPORTING_SERVER/result
+      echo "Failing job"
+      exit -1
+      )
+
   artifacts:
     code_format_patch:
       paths:
